### ISSUE TITLE
Does meteor-bootstrap work with demeteorizer?

### ISSUE THREAD

**Issue by gerwinbrunner** [Nemo64/meteor-bootstrap#11]
Hi,

I just added nemo64:bootstrap to my project and locally it works fine.
When I pack it with [demeteorizer](https://github.com/onmodulus/demeteorizer) and run it with standalone node it seems that no styles are loaded.

Should this work? What could I do wrong here?

Best,
Gerwin

**Comment by petermikitsh** [comment]
Point of clarification here: Is it even possible to have these files generated as part of the `meteor build` command? I'm looking to transition from manual to automated deploys. Since I currently gitignore `custom.bootstrap.less` and `custom.bootstrap.mixins.import.less`, I have to run `meteor`, quit some arbitrary amount of time later (after the files are generated), then run `meteor build ...`.

**Comment by emgee3** [comment]
Out of curiosity, why do you .gitignore the files? Because it should just work™ if you check them in to your vcs.

**Comment by petermikitsh** [comment]
Why I gitignore `custom.bootstrap.less` and `custom.bootstrap.mixins.import.less`:

- These files are a transformation of existing files from the project. To include them would dilute commit logs, which is unwanted when they become necessary to review. In some sense, it is a violation of DRY principles to include them.
- Prevent corner case deployment issues, like if a developer somehow doesn't check in a new version of `custom.bootstrap.mixins.import.less`, but edits one of its dependencies. By excluding them, it is ensured they are re-built when a new version of the app goes into production.

It would be appropriate to build these files when `meteor build` is run. Just because including these files directly into VC works, does not imply that is the best engineering practice to do so.

**Comment by emgee3** [comment]
Ok, I see where you're coming from. From a philosophical perspective I agree with you, but from a practical one, I'd suggest just checking in the files. 

The short answer to your original question is this is a limitation of Meteor's build plugin system. The bootstrap package does in fact create these files when running `meteor build`, but at that point of the build process it's too late for them to be processed. You could work around by running the build process twice (ick).

The good news is MDG is exploring new ways of handling LESS and other CSS preprocessors. [hackpad](https://meteor.hackpad.com/Improvements-to-LESS-and-other-CSS-preprocessors-fqDPbgOH8Fn)
