### ISSUE TITLE
load order glyphicon->forms

### ISSUE THREAD

**Issue by paulbalomiri** [Nemo64/meteor-bootstrap#44]
Hi, I run into a problem with displaying `form-group`s with `has-feedback` classes. 

Namely the `.form-control-feedback` selector must override the `.glyphicon` selector.

Simply chinging the order in `custom.bootstrap.json` solved the problem for me.

My json file has now this relative order amoungst `glyphicons` and `forms` import references.
```
{"modules": {
  ...
  "glyphicons":           true,
  "forms":                true,
 ...
}}
```

Perhaps this change should be written into the file generator.

great Package!

**Comment by emgee3** [comment]
I updated the JSON file to match the sequence Bootstrap lists the components. 

Because of how the package works, this doesn't retroactively fix the bug on existing installs — the change doesn't alter anyone's `custom.bootstrap.json`. That means that anyone with the incorrect sequence in their `custom.bootstrap.json` would need to manually change it.

However, for new installs the sequence is correct.

This change was published in `nemo64:bootstrap@3.3.4_2`.

**Comment by simison** [comment]
@emgee3 Let's add CHANGELOG.md to reflect this sort of stuff?

**Comment by emgee3** [comment]
Just thinking that :)

**Comment by simison** [comment]
:+1: Thanks for maintaining this btw!

**Comment by paulbalomiri** [comment]
Thanks for the quick fix!

**Comment by emgee3** [comment]
Welcome, all!
