### ISSUE TITLE
Row overflow with grid system

### ISSUE THREAD

**Issue by Orbyt** [Nemo64/meteor-bootstrap#45]
Issue from meteor forums:

Using 3 'col-md-4' in a row, the third column overflows. 

Code: 
```html
<template name="entries">
	<div class="row">
		{{#each entry}}
			<div class="entries col-md-4">
				<img src="{{pic}}">
			</div>
		{{/each}}
	</div>
</template>
```
result: http://prntscr.com/6skd9j

This is with the default package with only grid set to ```true``` in custom.bootstrap.json

@emgee3 this is the only bootstrap code im running.

**Comment by emgee3** [comment]
Hey @orbyt, looks like the issue is the lack of the `scaffolding` component in `custom.bootstrap.json`. If I add it, the columns flow properly. 

I made a reproduction here: https://github.com/emgee3/meteor-bootstrap-45 and by toggling scaffolding, it breaks or unbreaks the columns.

If you don't want to use the scaffolding, you'll have to copy the missing property from here: https://github.com/twbs/bootstrap/blob/master/less/scaffolding.less  — I didn't track down which one causes it.

Hope this helps!

**Comment by Orbyt** [comment]
I noticed that setting scaffolding to true seemed to work as well, but it resets alot of global variables in the process. Couldn't find in the less files what was causing it either =/. Thanks.
