### ISSUE TITLE
Error on applying upgrade patch

### ISSUE THREAD

**Issue by serkandurusoy** [Nemo64/meteor-bootstrap#57]
I get this

    sh: 5: set: Illegal option -o pipefail

when I run the upgrade patch.

**Comment by serkandurusoy** [comment]
I'm on ubuntu 14.04 64-bit using the built in terminal (with bash)

Commenting out `-o pipefail` helps, but I think it is advised to add the `-euf` flags as well, of which `e` and  `u` are already in place.

**Comment by emgee3** [comment]
Ok, so this is weird. I did actually test in Ubuntu 14.04, but not via curl, which is where I think the problem is. It looks like that while bash is the default shell in Ubuntu, when you execute a shell script, it uses dash instead. Fortunately, the fix is easy, pipe the script into bash directly:

```
curl https://raw.githubusercontent.com/Nemo64/meteor-bootstrap/master/upgrade/upgrade-3.3.4-3.3.5.sh | /bin/bash
```

I did add the -f flag, by the way. Thanks!

**Comment by serkandurusoy** [comment]
:8ball:
